spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/KFDB
#    username: postgres
#    password: 1234
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
